components/Benefits.jsx, pages/index.jsx
=> Content update

components/Header.tsx, components/Link.tsx, pages/_document.tsx
=> improve responsive navigation accessibility

src/pages/index.hbs
=> remove 6 month for free

.github/dependabot.yml
=> Add github actions dependency updates

src/pages/impressum.hbs, src/partials/footer.hbs
=> fix copy right to fss gmbh

package-lock.json, package.json, snowpack.config.js
=> add snowpack-plugin-cache-bust

src/demo.hbs
=> switch to new demo system

src/impressum.md
=> use Ust-Id instead of Steuernummer in impressum

src/_includes/partials/footer.hbs, src/impressum.md
waiting for https://github.com/focus-shift/bureau/issues/85#issuecomment-751879877
=> Add phone number to footer and impressum

src/_includes/layout-index.hbs, src/_includes/layout-subpage.hbs, src/_includes/partials/support-chat.hbs
=> Support chat

src/_includes/partials/price.hbs
=> offnes -> offenes

src/_includes/partials/price.hbs, src/faq.hbs, src/index.hbs
=> Improve texts

src/_includes/layout.hbs
=> fix cross origin for support css preload

src/_includes/partials/navigation.hbs
=> add login button

src/index.hbs
=> make whole stage on index page linkable

src/_includes/partials/navigation.hbs, static/css/style.css
=> Fix navigation html

src/_includes/partials/drei-monate-kostenlos-badge.hbs, src/_includes/partials/price.hbs, src/index.hbs
=> Add badge to price page

src/_includes/partials/faq.hbs
=> update faq infos and fix typos

src/_includes/partials/footer.hbs, src/_includes/partials/icon-feed.hbs
=> Add rss feed to landing page footer

src/404.hbs
=> Add 404 page

src/404.hbs
=> Fix links on 404

src/neuigkeiten/2021-10-20-release/index.md, src/neuigkeiten/2021-11-16-release/index.md, src/neuigkeiten/2021-11-19-release/index.md
=> Updates: change title with subtitle

src/neuigkeiten/2021-12-03-release/index.md
=> Blog 4.27.1/2/3

src/sitemap.njk
=> Remove draft from sitemap

package-lock.json, package.json, postcss.config.js, src/_includes/layout-neuigkeiten.hbs, src/_includes/layout-wissensbasis.hbs, src/hilfe/index.hbs, src/index.hbs, tailwind.config.js
=> upgrade tailwind to v3

src/_includes/partials/drei-monate-kostenlos-badge.hbs, src/_includes/partials/price.hbs, src/index.hbs
=> remove "Starte digital in 2022" promotion

src/hilfe/benutzer/benutzer.md
=> Add help about profile avatar and gravatar

src/demo.hbs
=> track demo clicks

src/hilfe/feiertage/feiertage.md
=> add DACH Region

src/_includes/partials/ein-monat-kostenlos-badge.hbs, src/_includes/partials/price.hbs, src/index.hbs
=> Sommerurlaub Aktion

src/hilfe/benutzer/benutzer.md
=> Change hilfe for adaption of berechtigungen

src/demo.hbs, src/hilfe/ueberstunden/ueberstunden.md
=> Aus Rolle wird Berechtigung

src/hilfe/onboarding/onboarding.md
=> Improved onboarding section for invite

src/neuigkeiten/2021-02-05-release/index.md, src/neuigkeiten/2021-02-09-release/index.md, src/neuigkeiten/2021-02-20-release/index.md, src/neuigkeiten/2021-03-08-release/index.md, src/neuigkeiten/2021-03-26-release/index.md, src/neuigkeiten/2021-04-09-release/index.md, src/neuigkeiten/2021-10-20-release/index.md, src/neuigkeiten/2021-11-16-release/index.md, src/neuigkeiten/2021-11-19-release/index.md, src/neuigkeiten/2021-12-15-release/index.md, src/neuigkeiten/2022-01-12-release/index.md, src/neuigkeiten/2022-02-06-release/index.md, src/neuigkeiten/2022-03-11-release/index.md, src/neuigkeiten/2022-03-23-release/index.md, src/neuigkeiten/2022-03-24-release/index.md, src/neuigkeiten/2022-03-31-release/index.md, src/neuigkeiten/2022-04-06-release/index.md, src/neuigkeiten/2022-04-27-release-4.35.0/index.md, src/neuigkeiten/2022-06-01-release-4.39.0/index.md, src/neuigkeiten/2022-07-22-release-4.43.0/index.md
=> Remove update image from all blog posts with updates

package-lock.json, package.json, postcss.config.js
=> minify css

src/_includes/partials/price.hbs
=> add on-premise info to price section

package-lock.json, package.json, src/_includes/partials/support-chat.hbs
=> load jquery from urlaubsverwalung.cloud

src/_includes/partials/price.hbs, src/_includes/partials/zwei-monate-kostenlos-badge.hbs, src/index.hbs
=> add info for digital new year 2023 promotion

src/_includes/layout-subpage.hbs, src/_includes/layout.hbs, src/_includes/meta.hbs, src/index.hbs
=> improve seo

src/_includes/partials/zwei-monate-kostenlos-badge.hbs, src/index.hbs
Titel und Preisbadge für Black friday
=> black friday

src/agb.md
=> add customer reference permission to agb

src/_includes/partials/zwei-monate-kostenlos-badge.hbs, src/index.hbs
This reverts commit a6db3910e7421086991e2f11b42924363fcb5f74.
=> Revert "black friday"

src/neuigkeiten/2022-12-05-zeiterfassung/index.md
=> Blogartikel Zeiterfassung

src/_includes/partials/faq.hbs, src/_includes/partials/navigation.hbs, src/hilfe/sso/azuread/azuread.md
=> "Anmelden" will be "Login"

src/zeiterfassung.hbs
=> Extend beta test period zeiterfassung

src/zeiterfassung.hbs
=> Improve wording

public/static/references/hermanns.svg, public/static/references/mathes.svg
=> fix invisible logos in firefox

src/index.hbs
=> responsive open-source section layout

src/neuigkeiten/2023-01-20-opensource-vs-datenschutz/index.md
=> improve open source blog

src/index.hbs, src/zeiterfassung.hbs
=> Zeiterfassung roadmap update 1.1.0

src/demo.hbs
=> Switch users

src/index.hbs
=> fix div structure

src/zeiterfassung.hbs
=> update features and roadmap

src/neuigkeiten/2023-01-20-opensource-vs-datenschutz/index.md, src/neuigkeiten/2023-02-23-zeiterfassung-arbeitszeiten/index.md, src/static/css/neuigkeiten.css
=> Add margin top and bottom to h2

src/demo.hbs
=> Update demo system urls to new demo system

src/demo.hbs
=> Add link demo zeiterfassung

src/index.hbs
=> Fix open source grid on small devices

package.json, src/_includes/partials/support-chat.hbs, src/static/js/zammad.js
This reverts commit 3155c7091aeb2f3d7c7f59d9c6e5340154a9fb95.
=> Introduce zammad chat with defered loading of the javascript

src/zeiterfassung.hbs
=> Extend zeiterfassung beta period

src/index.hbs, src/neuigkeiten/index.hbs
=> Add lazy loading to entry page

src/hilfe/feiertage/feiertage.md
=> Add new public holidays to help

src/hilfe/sso/azuread/azuread.md, src/hilfe/sso/google/google.md, src/hilfe/sso/sso.md
=> add google workspace sso section

src/hilfe/benutzer/benutzer.md
=> Add section about deactivation of gravatar

src/_includes/layout.hbs
=> custom domains are gone for plausible

src/index.hbs
=> fix spelling

src/hilfe/feiertage/feiertage.md
=> Add public holidays of the netherlands

src/demo.hbs, src/index.hbs, src/preis.hbs
=> add calendly

src/neuigkeiten/2024-05-10-uv-v5/index.md
=> Update v5 blog with ze integration

package-lock.json, package.json, src/_includes/google-tag-manager-body.hbs, src/_includes/google-tag-manager-head.hbs, src/_includes/klaro-cookie-consent.hbs, src/_includes/layout.hbs, src/_includes/partials/cookie-button.hbs, src/static/css/klaro.css, src/static/js/klaro.js
=> add klaro cookie consent

.eleventy.js, src/_includes/layout-neuigkeiten.hbs, src/faq.html, src/feed.njk, src/funktionen.hbs, src/neuigkeiten/index.hbs, src/sitemap.njk
=> Unify publication date

src/neuigkeiten/2024-10-02-release-5.8.0/index.md
=> Improve blogs

package.json, postcss.config.js, src/neuigkeiten/neuigkeiten.11tydata.js, tailwind.config.js
=> cjs to mjs

.github/workflows/build-and-deploy.yml, .github/workflows/calibreapp-image-actions.yml, .github/workflows/issue-deplanned.yml, .github/workflows/issue-planned.yml, .github/workflows/issue-stale.yml, .github/workflows/link-checker-external.yml
=> Upgrade runner to ubuntu 24.04

src/demo.hbs
=> Demo nofollow

src/android-app.hbs, src/branchen/agenturen.hbs, src/branchen/apotheken.hbs, src/branchen/arztpraxen.hbs, src/branchen/bau.hbs, src/branchen/e-commerce.hbs, src/branchen/einzelhandel.hbs, src/branchen/gesundheit-yoga.hbs, src/branchen/ingenieurbuero.hbs, src/branchen/logistik-handel.hbs, src/branchen/notariat-kanzleien.hbs, src/branchen/oeffentliche-verwaltung.hbs, src/branchen/pflegeeinrichtungen.hbs, src/branchen/software-hardware.hbs, src/branchen/verlag.hbs, src/branchen/versicherungen.hbs, src/demo.hbs, src/index.hbs, src/individuell.hbs, src/kalenderintegration.hbs, src/mental-health.hbs, src/mental-health/akutes-problem-mentale-gesundheit.hbs, src/mental-health/arbeitszeiten-mentale-gesundheit.hbs, src/mental-health/fehlzeiten-mentale-gesundheit.hbs, src/mental-health/handlungsempfehlungen-mentale-gesundheit.hbs, src/mental-health/selbstwahrnehmung-mentale-gesundheit.hbs, src/uebersicht.hbs, src/zeiterfassung.hbs
=> Fix image links

.github/workflows/build-and-deploy.yml
=> Build and deploy with new linkchecker

src/index.hbs, src/opensource/digitale-souveraenitaet.hbs, src/opensource/innovation-durch-community.hbs, src/opensource/sicherheit-durch-transparenz.hbs
=> Fix links without slash at the end

src/zeiterfassung.hbs
=> New feature: sync for overtime

.github/workflows/build-and-deploy.yml
=> unify dist directory

src/datenschutz.hbs
=> Improve datenschutz
